# Generated by Django 5.0.1 on 2024-01-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='slug',
        ),
    ]
